FROM node:20.17-alpine3.20

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps

COPY packages ./packages

RUN npm install

RUN npm run db:generate

RUN npm run build --filter=webhook-server

CMD ["npm","run","start-webhook-server"] 
